This is excercise on regression and it covers
1. Finding the cost
2. finding gradient descent
3. feature scaling
4. predict for a dataset that's not seen before or classify the dataset for training and for prediction

In [1]:
import numpy as np
import copy

In [2]:
def load_house_data():
    data = np.loadtxt("./data/houses.txt", delimiter=',', skiprows=1)
    X = data[:,:4]
    y = data[:,4]
    return X, y
X,y = load_house_data()
print(X,y)

[[1.244e+03 3.000e+00 1.000e+00 6.400e+01]
 [1.947e+03 3.000e+00 2.000e+00 1.700e+01]
 [1.725e+03 3.000e+00 2.000e+00 4.200e+01]
 [1.959e+03 3.000e+00 2.000e+00 1.500e+01]
 [1.314e+03 2.000e+00 1.000e+00 1.400e+01]
 [8.640e+02 2.000e+00 1.000e+00 6.600e+01]
 [1.836e+03 3.000e+00 1.000e+00 1.700e+01]
 [1.026e+03 3.000e+00 1.000e+00 4.300e+01]
 [3.194e+03 4.000e+00 2.000e+00 8.700e+01]
 [7.880e+02 2.000e+00 1.000e+00 8.000e+01]
 [1.200e+03 2.000e+00 2.000e+00 1.700e+01]
 [1.557e+03 2.000e+00 1.000e+00 1.800e+01]
 [1.430e+03 3.000e+00 1.000e+00 2.000e+01]
 [1.220e+03 2.000e+00 1.000e+00 1.500e+01]
 [1.092e+03 2.000e+00 1.000e+00 6.400e+01]
 [8.480e+02 1.000e+00 1.000e+00 1.700e+01]
 [1.682e+03 3.000e+00 2.000e+00 2.300e+01]
 [1.768e+03 3.000e+00 2.000e+00 1.800e+01]
 [1.040e+03 3.000e+00 1.000e+00 4.400e+01]
 [1.652e+03 2.000e+00 1.000e+00 2.100e+01]
 [1.088e+03 2.000e+00 1.000e+00 3.500e+01]
 [1.316e+03 3.000e+00 1.000e+00 1.400e+01]
 [1.593e+03 0.000e+00 1.000e+00 2.000e+01]
 [9.720e+02

In [3]:
print(X.shape) # 4 features and 99 trainig examples
print(y.shape) # price of 99 training examples

print("First training data",X[0])
print("Price of first training data",y[0])

(99, 4)
(99,)
First training data [1.244e+03 3.000e+00 1.000e+00 6.400e+01]
Price of first training data 300.0


In [4]:
# what does cost mean
# sum of all cost = f_yi - yi ** 2 / m
def compute_cost (X,y,w,b):
    # m,n = X.shape
    # cost = 0.0
    # for i in range(m):
    #     f_wb_i = w * X[i] + b if n == 1 else np.dot(X[i],w) + b
    #     cost += (f_wb_i - y[i]) ** 2
    # total_cost = 1 / (2 * m * cost)
    # return total_cost
    m = X.shape[0]
    cost = 0.0
    for i in range(m):                                
        f_wb_i = np.dot(X[i],w) + b       
        cost = cost + (f_wb_i - y[i])**2              
    cost = cost/(2*m)                                 
    return(np.squeeze(cost)) 


In [5]:
np.dot([18.145],[0]) + 1.245

1.245

- The next step is to compute gradient descent and update w and b until convergence
- So how do you compute w and b
- The best w and b makes cost zero
- So we need to find the derivative of dj/dw and dj/db, J being the cost function
- what is J = 1/2*sum((X[i]*W[i] + b - y[i]) ** 2)
- if we assume error = X[i]*W[i] + b - y[i]
- J will be J = (error) ** 2
- Now, by the chain rule finding dj/derr and derr/dw  and multiplying will give dj/dw
- So, what is dj/derr = 2 * err (power rule of derivative) and what is derr/dw = X[i] (product rule of derivative)
- Therefore dj/dw = err * x[i][j]
- and with the same approch dj/db = err

In [40]:
def compute_gradient(X,y,w,b):
    m,n = X.shape
    # dj_dw = np.zeros(n) # weight of each feature
    dj_dw = 0.0 if n == 1 else np.zeros(n) # weight of each feature
    dj_db = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i],w) + b
        err = f_wb_i - y[i]
        if n > 1:
            for j in range(n):
                dj_dw[j] += (err * X[i][j])
        else: dj_dw += err * X[i] 
        dj_db += err
    return dj_db/m,dj_dw/m

In [39]:
# so since dj_dw and dj_db tells us in which direction we should go
# let's update w and b with according to dj_dw and dj_db
def gradient_descent (X,y,w_init,b_init,iteration,alpha):
    w = copy.deepcopy(w_init)
    b = b_init
    for i in range(iteration):
        dj_db,dj_dw = compute_gradient(X,y,w,b)
        w = w - (alpha * dj_dw)
        b = b - (alpha * dj_db)
        
        if i % 100 == 0:
            cost = compute_cost(X,y,w,b)
            print(f"Cost at {i} iterations is: {cost}:")
        # cost = compute_cost(X,y,w,b)
        # print(f"Cost at {i} iterations is: {cost}:")
    print("final result of w",w,"final result of b",b)
    return w,b

In [12]:
# iteration = 1001
iteration = 10
# alpha = 1e-7
alpha = 1e-7
w_init = np.zeros(X.shape[1])
b_init = 0.0

w,b = gradient_descent(X,y,w_init,b_init,iteration,alpha)



Cost at 0 iterations is: 44231.26525678279:
Cost at 1 iterations is: 27646.11540274138:
Cost at 2 iterations is: 17510.224442092407:
Cost at 3 iterations is: 11315.74324982964:
Cost at 4 iterations is: 7530.0211455750805:
Cost at 5 iterations is: 5216.3916908889905:
Cost at 6 iterations is: 3802.419151959339:
Cost at 7 iterations is: 2938.2642947777135:
Cost at 8 iterations is: 2410.1258445063145:
Cost at 9 iterations is: 2087.340968967634:
final result of w [2.31283016e-01 4.17834784e-04 2.12498494e-04 4.80830049e-03] final result of b 0.00015472928633378463


In [13]:
m = X.shape[0]
for i in range(m):
    p = np.dot(X[i],w) + b
    print("prediction",p, "actual price",y[i])

prediction 288.0254243852543 actual price 300.0
prediction 450.39160730114634 actual price 509.8
prediction 399.16698516907104 actual price 394.0
prediction 453.1573868971556 actual price 540.0
prediction 303.97440267499803 actual price 415.0
prediction 200.14707691333479 actual price 230.0
prediction 424.7189799804646 actual price 560.0
prediction 237.50475249621127 actual price 294.0
prediction 739.1385276412537 actual price 718.2
prediction 182.63688387259882 actual price 200.0
prediction 277.62277620353206 actual price 302.0
prediction 360.1954088660797 actual price 468.0
prediction 330.8325002170018 actual price 374.2
prediction 282.2386074323761 actual price 388.0
prediction 252.86998805522282 actual price 282.0
prediction 196.21052409178537 actual price 311.8
prediction 389.13045775383046 actual price 401.0
prediction 408.9967556631555 actual price 449.8
prediction 240.74752302652877 actual price 301.0
prediction 382.1817203270857 actual price 502.0
prediction 251.80541527529027

- The Prediction is not so bad but it's also not so close to the target value
- Also, the cost is not decreasing by much after the 100th iteration.
- And that's because sqft feature w/c is X[i][0] is much larger than the other features
- So we need to use feature scaling to optimize that data
- And see if we can find a lower cost and accurate prediction than the previous iterations

In [14]:
def z_score_normalization (X):
    mean = np.mean(X,axis=0) # mean of the col, mean ill have shape (n,)
    sigma = np.std(X,axis=0) # the standard deviation of each column/feature
    X_norm = (X - mean)/sigma
    return X_norm,mean,sigma


In [17]:
X_norm,mean,sigma = z_score_normalization(X)
print(f"X_mu = {mean}, \nX_sigma = {sigma}")
print(f"Peak to Peak range by column in Raw X:{np.ptp(X,axis=0)}")   
print(f"Peak to Peak range by column in Normalized X:{np.ptp(X_norm,axis=0)}")
# After normalization feature[0] or sqft maximum is down to almost 6

X_mu = [1.41837374e+03 2.71717172e+00 1.38383838e+00 3.83838384e+01], 
X_sigma = [411.61562893   0.65196523   0.48631932  25.77788069]
Peak to Peak range by column in Raw X:[2.406e+03 4.000e+00 1.000e+00 9.500e+01]
Peak to Peak range by column in Normalized X:[5.8452591  6.13529646 2.05626214 3.68533012]


In [20]:
# now let's train our model with the normalized input data
alpha = 1.0e-1
iteration=1000
w_norm,b_norm = gradient_descent(X_norm,y,w_init,b_init,iteration,alpha)

Cost at 0 iterations is: 57617.03252196659:
Cost at 100 iterations is: 221.0856266404719:
Cost at 200 iterations is: 219.20890028987435:
Cost at 300 iterations is: 219.2068266767102:
Cost at 400 iterations is: 219.20682438502703:
Cost at 500 iterations is: 219.20682438249423:
Cost at 600 iterations is: 219.20682438249156:
Cost at 700 iterations is: 219.20682438249133:
Cost at 800 iterations is: 219.20682438249162:
Cost at 900 iterations is: 219.2068243824914:
final result of w [110.56039756 -21.26715096 -32.70718139 -37.97015909] final result of b 363.15608080808056


The scaled features get very accurate results much, much faster!. Notice the gradient of each parameter is tiny by the end of this fairly short run. A learning rate of 0.1 is a good start for regression with normalized features. Let's plot our predictions versus the target values. Note, the prediction is made using the normalized feature while the plot is shown using the original feature values.

In [21]:
m = X_norm.shape[0]
for i in range(m):
    p = np.dot(X_norm[i],w_norm) + b_norm
    print("prediction",p, "actual price",y[i])

prediction 295.176153014491 actual price 300.0
prediction 485.9779633156195 actual price 509.8
prediction 389.52416547712676 actual price 394.0
prediction 492.14712499067645 actual price 540.0
prediction 420.2470182541521 actual price 415.0
prediction 222.78186731046634 actual price 230.0
prediction 523.417783476759 actual price 560.0
prediction 267.55358319014005 actual price 294.0
prediction 685.1952161268126 actual price 718.2
prediction 181.74654412954288 actual price 200.0
prediction 317.9530344921217 actual price 302.0
prediction 479.62518007591024 actual price 468.0
prediction 409.94682655710835 actual price 374.2
prediction 393.52554342739234 actual price 388.0
prediction 286.96885968636377 actual price 282.0
prediction 323.28006626784327 actual price 311.8
prediction 405.96083370483524 actual price 401.0
prediction 436.42539770380677 actual price 449.8
prediction 269.8410237138005 actual price 301.0
prediction 500.7233582540422 actual price 502.0
prediction 328.61071386010894 

**Prediction** The point of generating our model is to use it to predict housing prices that are not in the data set. Let's predict the price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old. Recall, that you must normalize the data with the mean and standard deviation derived when the training data was normalized.

In [22]:
x_house = np.array([1200, 3, 1, 40])
# you should normalize with mean and standard deviation that you get from trainig data, you don't normalize by taking the mean and 
# standard deviation of prediction data itself b/c it doesn't make sense 
x_house_norm = (x_house - mean)/sigma
print(x_house_norm)
prediction = np.dot(x_house_norm,w_norm) + b_norm
prediction

[-0.53052829  0.43380884 -0.78927234  0.06269567]


318.7090923199992

# Feature Engineering

In [44]:
x = np.arange(0, 20, 1).reshape(-1,1)
y = 1 + x**2
y = y.reshape(20,)

w = np.zeros(x.shape[1])
print("w",w)
b = 0.0
iteration = 1000
alpha = 1e-2

w_model,b_model = gradient_descent(x,y,w,b,iteration,alpha)

w [0.]
Cost at 0 iterations is: 1657.5632937500002:
Cost at 100 iterations is: 694.5491067092513:
Cost at 200 iterations is: 588.4754483004803:
Cost at 300 iterations is: 526.4137606474569:
Cost at 400 iterations is: 490.10264314551796:
Cost at 500 iterations is: 468.8576963175959:
Cost at 600 iterations is: 456.42768047748433:
Cost at 700 iterations is: 449.1551137331723:
Cost at 800 iterations is: 444.9000727315512:
Cost at 900 iterations is: 442.41052886595054:
final result of w [18.69806954] final result of b -52.08341025448667


Well, as expected, not a great fit. What is needed is something like y = wx**2 + b, or a polynomial feature. To accomplish this, you can modify the input data to engineer the needed features. If you swap the original data with a version that squares the x value, then you can achieve y = wx**2 + b,
. Let's try it. Swap X for X**2 below:

In [ ]:
x = np.arange(0,20,1).reshape(-1,1)
y = 1 + x**2

#  Engineer features 
X = x**2      #<-- added engineered feature
iteration = 10000
alpha=1e-5
w_model,b_model = gradient_descent(X,y,w,b,iteration,alpha)

Great! near perfect fit. Notice the values of 
 and b printed right above the graph: w,b found by gradient descent: w: [1.], b: 0.0490. Gradient descent modified our initial values of 
 to be (1.0,0.049) or a model of 
, very close to our target of 
. If you ran it longer, it could be a better match.

## Selecting Features

Above, we knew that an x**2 term was required. It may not always be obvious which features are required. One could add a variety of potential features to try and find the most useful. For example, what if we had instead tried : y = wx1 + wx2**2 + y = wx2**3
 ?

In [51]:
# create target data
x = np.arange(0, 20, 1)
y = x**2

# engineer features .
X = np.c_[x, x**2, x**3]   #<-- added engineered feature

In [52]:
iteration = 10000
alpha=1e-7
w = np.zeros(X.shape[1])
w_model,b_model = gradient_descent(X,y,w,b,iteration,alpha)

Cost at 0 iterations is: 1140.2924039588138:
Cost at 100 iterations is: 378.84024762689825:
Cost at 200 iterations is: 372.8909233165143:
Cost at 300 iterations is: 367.035031236854:
Cost at 400 iterations is: 361.27110406458786:
Cost at 500 iterations is: 355.59769752022976:
Cost at 600 iterations is: 350.01339000624205:
Cost at 700 iterations is: 344.5167822508214:
Cost at 800 iterations is: 339.106496957282:
Cost at 900 iterations is: 333.7811784589415:
Cost at 1000 iterations is: 328.5394923794302:
Cost at 1100 iterations is: 323.3801252983334:
Cost at 1200 iterations is: 318.30178442208273:
Cost at 1300 iterations is: 313.30319726002165:
Cost at 1400 iterations is: 308.3831113055514:
Cost at 1500 iterations is: 303.54029372228985:
Cost at 1600 iterations is: 298.77353103515617:
Cost at 1700 iterations is: 294.0816288263075:
Cost at 1800 iterations is: 289.4634114358522:
Cost at 1900 iterations is: 284.9177216672618:
Cost at 2000 iterations is: 280.4434204974085:
Cost at 2100 itera

Note the value of w, [0.08 0.54 0.03] and b is 0.0106.This implies the model after fitting/training is:

0.08x + 0.54x**2 + 0.03x**3 + 0.0106


Let's review this idea:
- Intially, the features were re-scaled so they are comparable to each other
- less weight value implies less important/correct feature, and in extreme, when the weight becomes zero or very close to zero, the associated feature useful in fitting the model to the data.
- above, after fitting, the weight associated with the $x^2$ feature is much larger than the weights for $x$ or $x^3$ as it is the most useful in fitting the data. 

# Scikit-learn linear regression implementation

In [55]:
from sklearn.linear_model import LinearRegression,SGDRegressor # gradient descent regression model
from sklearn.preprocessing import StandardScaler # This will perform z-score normalization

In [56]:
def load_house_data():
    data = np.loadtxt("./data/houses.txt", delimiter=',', skiprows=1)
    X = data[:,:4]
    y = data[:,4]
    return X, y
X,y = load_house_data()

## normalize the training data

In [58]:
scaler = StandardScaler()
X_norm = scaler.fit_transform(X)

print(f"Peak to Peak range by column in Raw        X:{np.ptp(X,axis=0)}")   
print(f"Peak to Peak range by column in Normalized X:{np.ptp(X_norm,axis=0)}")

Peak to Peak range by column in Raw        X:[2.406e+03 4.000e+00 1.000e+00 9.500e+01]
Peak to Peak range by column in Normalized X:[5.8452591  6.13529646 2.05626214 3.68533012]


## create and fit the regression model

In [60]:
sgdr = SGDRegressor(max_iter=1000)
sgdr.fit(X_norm, y)
print(sgdr)
print(f"number of iterations completed: {sgdr.n_iter_}, number of weight updates: {sgdr.t_}")

SGDRegressor()
number of iterations completed: 123, number of weight updates: 12178.0


## View Parameters


Note, the parameters are associated with the *normalized* input data. The fit parameters are very close to those found in the above example with this data.

In [61]:
b_norm = sgdr.intercept_
w_norm = sgdr.coef_
print(f"model parameters:                   w: {w_norm}, b:{b_norm}")
print(f"model parameters from previous lab: w: [110.56 -21.27 -32.71 -37.97], b: 363.16")

model parameters:                   w: [110.11738399 -21.0391742  -32.4421159  -38.04502188], b:[363.15841409]
model parameters from previous lab: w: [110.56 -21.27 -32.71 -37.97], b: 363.16


## Make predictions

Predict the targets of the training data. Use both the `predict` routine and compute using $w$ and $b$.

In [62]:
# make a prediction using sgdr.predict()
y_pred_sgd = sgdr.predict(X_norm)
# make a prediction using w,b. 
y_pred = np.dot(X_norm, w_norm) + b_norm  
print(f"prediction using np.dot() and sgdr.predict match: {(y_pred == y_pred_sgd).all()}")

print(f"Prediction on training set:\n{y_pred[:4]}" )
print(f"Target values \n{y[:4]}")

prediction using np.dot() and sgdr.predict match: True
Prediction on training set:
[295.18145756 485.9081823  389.62071486 492.07023692]
Target values 
[300.  509.8 394.  540. ]


## Linear regression, Closed-form solution

A closed form solution is a formula that can be used to find the optimal parameters for a linear regression model without using an iterative algorithm

In [63]:
X_train = np.array([1.0, 2.0])   #features
y_train = np.array([300, 500])   #target value

In [67]:
linear_model = LinearRegression()
#X must be a 2-D Matrix/
linear_model.fit(X_train.reshape(-1, 1), y_train) 

LinearRegression()

## View Parameters 
The $\mathbf{w}$ and $\mathbf{b}$ parameters are referred to as 'coefficients' and 'intercept' in scikit-learn.

In [66]:
b = linear_model.intercept_
w = linear_model.coef_
print(f"w = {w:}, b = {b:0.2f}")
print(f"'manual' prediction: f_wb = wx+b : {1200*w + b}")

w = [200.], b = 100.00
'manual' prediction: f_wb = wx+b : [240100.]


## Make Predictions

Calling the `predict` function generates predictions.

In [68]:
y_pred = linear_model.predict(X_train.reshape(-1, 1))

print("Prediction on training set:", y_pred)

X_test = np.array([[1200]])
print(f"Prediction for 1200 sqft house: ${linear_model.predict(X_test)[0]:0.2f}")

Prediction on training set: [300. 500.]
Prediction for 1200 sqft house: $240100.00


## Second Example
The second example is from an earlier lab with multiple features. The final parameter values and predictions are very close to the results from the un-normalized 'long-run' from that lab. That un-normalized run took hours to produce results, while this is nearly instantaneous. The closed-form solution work well on smaller data sets such as these but can be computationally demanding on larger data sets. 
>The closed-form solution does not require normalization.

In [70]:
linear_model = LinearRegression()
linear_model.fit(X, y) 

LinearRegression()

In [71]:
b = linear_model.intercept_
w = linear_model.coef_
print(f"w = {w:}, b = {b:0.2f}")

w = [  0.26860107 -32.62006902 -67.25453872  -1.47297443], b = 220.42


In [72]:
print(f"Prediction on training set:\n {linear_model.predict(X)[:4]}" )
print(f"prediction using w,b:\n {(X @ w + b)[:4]}")
print(f"Target values \n {y[:4]}")

x_house = np.array([1200, 3,1, 40]).reshape(-1,4)
x_house_predict = linear_model.predict(x_house)[0]
print(f" predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = ${x_house_predict*1000:0.2f}")

Prediction on training set:
 [295.17615301 485.97796332 389.52416548 492.14712499]
prediction using w,b:
 [295.17615301 485.97796332 389.52416548 492.14712499]
Target values 
 [300.  509.8 394.  540. ]
 predicted price of a house with 1200 sqft, 3 bedrooms, 1 floor, 40 years old = $318709.09
