# mulitclass classification - softmax

In [1]:
import numpy as np
from sklearn.datasets import make_blobs
import tensorflow as tf

In [2]:
def my_softmax(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return sm

In [3]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [4]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(25,activation="relu"),
    tf.keras.layers.Dense(15,activation="relu"),
    tf.keras.layers.Dense(4,activation="softmax")
])

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2023-03-21 14:53:59.600601: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-03-21 14:53:59.601064: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [5]:
# model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(),optimizer=tf.keras.optimizers.Adam(0.001))
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

In [6]:
# model.fit(X_train,y_train,epochs=10)
model.fit(
    X_train,y_train,
    epochs=10
)

Epoch 1/10


2023-03-21 14:54:16.515773: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-03-21 14:54:16.991336: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


63/63 [==============================] - 1s 5ms/step - loss: 0.9252
Epoch 2/10
63/63 [==============================] - 0s 4ms/step - loss: 0.3509
Epoch 3/10
63/63 [==============================] - 0s 4ms/step - loss: 0.1605
Epoch 4/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0992
Epoch 5/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0745
Epoch 6/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0613
Epoch 7/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0534
Epoch 8/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0479
Epoch 9/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0436
Epoch 10/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0397


In [10]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

 1/63 [..............................] - ETA: 14s

2023-03-21 15:09:50.960099: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


63/63 [==============================] - 0s 2ms/step
[[9.4512915e-03 1.2309392e-03 9.6986818e-01 1.9449603e-02]
 [9.9541157e-01 4.3963902e-03 7.7274126e-05 1.1478692e-04]]
largest value 0.9999987 smallest value 6.8088424e-11


## Prefered

In [15]:
preferred_model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(25,activation="relu"),
    tf.keras.layers.Dense(15,activation="relu"),
    tf.keras.layers.Dense(4,activation="linear"),
])

In [16]:
preferred_model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001))

In [17]:
preferred_model.fit(X_train,y_train,epochs=10)

Epoch 1/10
24/63 [==========>...................] - ETA: 0s - loss: 1.1430

2023-03-21 15:11:31.289130: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


63/63 [==============================] - 0s 5ms/step - loss: 0.9058
Epoch 2/10
63/63 [==============================] - 0s 4ms/step - loss: 0.4361
Epoch 3/10
63/63 [==============================] - 0s 4ms/step - loss: 0.1867
Epoch 4/10
63/63 [==============================] - 0s 4ms/step - loss: 0.1001
Epoch 5/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0681
Epoch 6/10
63/63 [==============================] - 0s 4ms/step - loss: 0.0540
Epoch 7/10
63/63 [==============================] - 0s 5ms/step - loss: 0.0460
Epoch 8/10
63/63 [==============================] - 0s 6ms/step - loss: 0.0408
Epoch 9/10
63/63 [==============================] - 0s 6ms/step - loss: 0.0371
Epoch 10/10
63/63 [==============================] - 0s 5ms/step - loss: 0.0341


In [18]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 2ms/step
two example output vectors:
 [[-0.70801497 -1.0307316   4.1313014  -0.10231146]
 [ 8.591696    1.828611   -3.0394797  -4.762278  ]]
largest value 16.35105 smallest value -9.243338


2023-03-21 15:11:45.902785: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


The output predictions are not probabilities! If the desired output are probabilities, the output should be be processed by a softmax.

In [23]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[7.6958807e-03 5.5731949e-03 9.7262788e-01 1.4103014e-02]
 [9.9883515e-01 1.1543125e-03 8.8743891e-06 1.5846630e-06]]
largest value 1.0 smallest value 7.664755e-12
m -0.70801497
my_softmax 1.0


To select the most likely category, the softmax is not required. One can find the index of the largest output using np.argmax().

In [21]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-0.70801497 -1.0307316   4.1313014  -0.10231146], category: 2
[ 8.591696   1.828611  -3.0394797 -4.762278 ], category: 0
[ 6.13415    2.0857482 -2.2284007 -4.050535 ], category: 0
[-1.3693347  4.494403  -0.2579732 -2.935954 ], category: 1
[ 1.9146984  -0.64026713  7.1323204  -3.9856515 ], category: 2
